//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiTrade {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class AppSetings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSetings defaultInstance = ((AppSetings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSetings())));
        
        public static AppSetings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BittrexApiKey {
            get {
                return ((string)(this["BittrexApiKey"]));
            }
            set {
                this["BittrexApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BittrexApiSecret {
            get {
                return ((string)(this["BittrexApiSecret"]));
            }
            set {
                this["BittrexApiSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BinanceApiKey {
            get {
                return ((string)(this["BinanceApiKey"]));
            }
            set {
                this["BinanceApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BinanceApiSecret {
            get {
                return ((string)(this["BinanceApiSecret"]));
            }
            set {
                this["BinanceApiSecret"] = value;
            }
        }
    }
}
